name: Firebase App Distribution

on:
  workflow_dispatch: # 수동으로 작업 실행

jobs:
  deploy-android-app-distribution:
    runs-on: ubuntu-latest # Ubuntu 최신 버전에서 실행

    steps:
    - uses: actions/checkout@v2 # 저장소 코드를 체크아웃

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # 필요에 따라 Ruby 버전을 조정하세요.

    - name: Install Fastlane # fastlane 설치
      run: |
        gem install fastlane
    
    - name: Install Flutter # flutter sdk 설치
      run: |
        git clone https://github.com/flutter/flutter.git -b 3.16.0 $HOME/flutter
        echo 'PATH="$HOME/flutter/bin:$PATH"' >> ~/.zshrc
    
    - name: Run Fastlane # fastlane 레인 실행
      run: |
        cd android
        fastlane distribute