name: Firebase App Distribution

on:
  workflow_dispatch: # 수동으로 작업 실행

jobs:
  deploy-android-app-distribution:
    runs-on: ubuntu-latest # Ubuntu 최신 버전에서 실행

    steps:
    - uses: actions/checkout@v2 # 저장소 코드를 체크아웃

    - name: Install Homebrew # homebrew 설치
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $GITHUB_ENV
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    - name: Install Fastlane # fastlane 설치
      run: brew install fastlane
    
    - name: Install Flutter # flutter sdk 설치
      run: |
        git clone https://github.com/flutter/flutter.git -b 3.16.0 $HOME/flutter
        echo 'export PATH="$PATH:$HOME/flutter/bin"' >> $GITHUB_ENV
        echo 'export PATH="$PATH:$HOME/flutter/bin/cache/dart-sdk/bin"' >> $GITHUB_ENV
        echo 'export PATH="$PATH:$HOME/.pub-cache/bin"' >> $GITHUB_ENV
        flutter pub get
    
    - name: Run Fastlane # fastlane 레인 실행
      run: |
        cd android
        fastlane distribute