name: Firebase App Distribution

on:
  workflow_dispatch: # 수동으로 작업 실행

jobs:
  deploy-android-app-distribution:
    runs-on: ubuntu-latest # Ubuntu 최신 버전에서 실행

    steps:
    - uses: actions/checkout@v2 # 저장소 코드를 체크아웃

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # 필요에 따라 Ruby 버전을 조정하세요.

    - name: Install Fastlane # fastlane 설치
      run: |
        gem install fastlane
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0' # 원하는 Flutter 버전을 설정합니다.
    
    - name: Run Fastlane # fastlane 레인 실행
      run: |
        flutter pub get
        cd android
        fastlane distribute